spring:
  application:
    name: notification-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${google_email}
    password: ${google_password}

    properties:
      mail:
        smtp:
          ssl:
            enable: true